### ISSUE TITLE
FHIR: Class Not Found exception trying to connect to SMART on FHIR - Restricted

### ISSUE THREAD

**Issue by michelemottini** [sparseware/ccp-bellavista#4]
![image](https://cloud.githubusercontent.com/assets/1046280/13480039/1c98887e-e0a9-11e5-9db6-dd5c56e6f436.png)

**Comment by sparseware** [comment]
Are you running the required version of Java 8

**Comment by michelemottini** [comment]
Wrong Java version, now it works

Thanks
