### ISSUE TITLE
Is there a way to log HTTP traffic?

### ISSUE THREAD

**Issue by michelemottini** [sparseware/ccp-bellavista#5]
On a log file or using Fiddler or any other tool? 

Tried using Fiddler setting the Java proxy but no luck.

I have some problems with the login sequence and I'd like to see what's going on to debug it

**Comment by sparseware** [comment]
No there isn't, you would have to debug using the source (of use a software based protocol sniffer). OAuth2 is the only authentication that it is known to work (was the only type of server I had access to). If you are using oAuth2, you would need to create a server entry similar to the 'SMART on FHIR - Restricted'  entry and  specifying the OAuth information. Also, make sure your conformance statement has the appropriate info/urls specified in the security section.

There was also a know issue with previous version of Java 8, verify you have the latest an greatest (You should be able to use to client to login to the 'SMART on FHIR - Restricted' server.

PS. If you have any other general questions please join and post them in the group this [group](http://groups.google.com/d/forum/clinical-client-platform)

**Comment by michelemottini** [comment]
OK, thanks!

**Comment by sparseware** [comment]
I added a message along with a jar file(and instructions for its use) in the message group that will allow you to do what you are asking.
